name: wallet

services:
  auth_service_application:
    build: ./AuthService
    container_name: auth_service_application_container
    ports:
      - "5050:${SERVER_PORT}"
    depends_on:
      auth_db:
        condition: service_healthy
    environment:
      - DB_URL=${DB_URL}
      - SECRET=${SECRET}
      - SERVER_PORT=${SERVER_PORT}
  
  auth_db:
    image: postgres:18-alpine
    container_name: auth_db_container
    ports:
      - "5432:${AUTH_DB_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_AUTH_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata_auth_db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", " pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_AUTH_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata_auth_db: {}