events {}

http {
    server {
        listen 443 ssl;
        location / {
            proxy_pass http://auth_service_application:8080;
            ssl_certificate     /etc/nginx/certs/server.crt;
            ssl_certificate_key /etc/nginx/certs/server.key;
        }
    }
}