events {}

http {
    server {
        listen 443 ssl;
        ssl_certificate     /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;
        gzip on;
        gzip_comp_level 5;
        gzip_min_length 1024;
        gzip_types
            application/json;
        add_header X-Frame-Options "DENY" always;
        add_header X-Content-Type "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        client_max_body_size 2M;
        keepalive_timeout 65;
        proxy_connect_timeout 10s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;
        limit_req_zone $binary_remote_addr zone=auth:10m rate=5r/s;
        limit_req_zone $binary_remote_addr zone=register:10m rate=5r/s;
        location /validate {
            proxy_pass http://auth_service_application:8080;
        }
        location /auth {
            limit_req zone=auth burst=10 nodelay;
            proxy_pass http://auth_service_application:8080;
        }
        location /register {
            limit_req zone=register burst=10 nodelay;
            proxy_pass http://auth_service_application:8080;
        }
    }
}